CREATE TABLE todos_all
(
    id1 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id bigint,
    todo VARCHAR(255),
    is_completed BOOLEAN,
    priority int,
    CONSTRAINT pk_todo PRIMARY KEY (id1)
);